#????
server:
  port: 8002
#???
spring:
  application:
    name: service-oss
  #?????dev?test?prod
  profiles:
    active: dev


#??? OSS
#???????????
OSS:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tEawQ7krqZzuj2K6YXs
  accessKeySecret: 4Rt948uQZUtydwF2Qn5PerFGViFtZi
  bucketName: edu0010