#????
server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB


OSS:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId:
  bucketName: edu0010
